//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.11 at 08:18:29 PM AST 
//


package com.bookdb.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for bookS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="bookS">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bookIdS" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="isbnS" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="titleS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="priceS" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="descriptionS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bookS", propOrder = {
    "bookIdS",
    "isbnS",
    "titleS",
    "priceS",
    "descriptionS"
})
public class BookS {

    protected int bookIdS;
    protected int isbnS;
    @XmlElement(required = true)
    protected String titleS;
    protected double priceS;
    @XmlElement(required = true)
    protected String descriptionS;

    /**
     * Gets the value of the bookIdS property.
     * 
     */
    public int getBookIdS() {
        return bookIdS;
    }

    /**
     * Sets the value of the bookIdS property.
     * 
     */
    public void setBookIdS(int value) {
        this.bookIdS = value;
    }

    /**
     * Gets the value of the isbnS property.
     * 
     */
    public int getIsbnS() {
        return isbnS;
    }

    /**
     * Sets the value of the isbnS property.
     * 
     */
    public void setIsbnS(int value) {
        this.isbnS = value;
    }

    /**
     * Gets the value of the titleS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitleS() {
        return titleS;
    }

    /**
     * Sets the value of the titleS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitleS(String value) {
        this.titleS = value;
    }

    /**
     * Gets the value of the priceS property.
     * 
     */
    public double getPriceS() {
        return priceS;
    }

    /**
     * Sets the value of the priceS property.
     * 
     */
    public void setPriceS(double value) {
        this.priceS = value;
    }

    /**
     * Gets the value of the descriptionS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescriptionS() {
        return descriptionS;
    }

    /**
     * Sets the value of the descriptionS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescriptionS(String value) {
        this.descriptionS = value;
    }

}
